version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: museum_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Porta externa 5433 -> interna 5432

  backend:
    build: ./api-main
    container_name: go_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_URL: "postgresql://postgres:1234@postgres:5432/museum_db?sslmode=disable"
      PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: vite_frontend
    restart: always
    depends_on:
      - backend
    environment:
      # Importante: usar o nome do serviço backend, não localhost
      VITE_API_URL: "http://backend:8080"
    ports:
      - "3000:80"

volumes:
  postgres_data:
