# Etapa 1 - Build
FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o server main.go

# Etapa 2 - Run
FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/server .

# Porta lida via variável de ambiente
ENV PORT=8080
EXPOSE 8080

CMD ["./server"]
